struct { name = "person",
         fields = {
	    {name = "age",
	     type = "int"},
       {name = "name",
       type = "string"},
	 }
}
interface { name = "minhaInt",
            methods = {
               foo = {
                 resulttype = "double",
                 args = {{direction = "in",
                          type = "double"},
                         {direction = "in",
                          type = "void"},
                         {direction = "in",
                          type = "person"},
                         {direction = "out",
                          type = "int"}
                        }

               },
               boo = {
                 resulttype = "void",
                 args = {}
               }
             }
            }